### ISSUE TITLE
Correct README examples for Result and Generic Result of T

### ISSUE THREAD

**Issue by crobinson-expl** [NitroDevs/CSharpFunctionalExtensions.FluentAssertions#37]
Thanks, @KyleMcMaster for creating this project!  It has been nice to work with so far.  I noticed that there is mention of a `FailWith(...)` method in the examples for assertions of Result and Generic Result of T, but these methods do not exist.

![image](https://user-images.githubusercontent.com/84980421/224435451-9df9179a-f1aa-4213-8997-4a2318267373.png)

**Comment by KyleMcMaster** [comment]
@crobinson-expl First, I'd like to say thanks for using the library and opening an issue! I believe the README is actually correct and the functionality appears to be missing from the codebase possibly due to a bad merge or forgetting to PR a branch. I will get the `FailWith` methods added and release a new version as soon as possible.

**Comment by crobinson-expl** [comment]
> @crobinson-expl First, I'd like to say thanks for using the library and opening an issue! I believe the README is actually correct and the functionality appears to be missing from the codebase possibly due to a bad merge or forgetting to PR a branch. I will get the `FailWith` methods added and release a new version as soon as possible.

Sounds great, thanks @KyleMcMaster!
